name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
  push:
    branches:
      - master
      - main
      - devel
      - develop
      - development

jobs:
  build:
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    # container:
    #   image: node:latest

    # services:
    #   mongo:
    #     image: mongo:latest
    #     ports:
    #       - 27017:27017

    strategy:
      matrix:
        node-version: [19.x] #[16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: PRINT LS
        run: ls
      - name: Checkout
        uses: actions/checkout@main
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}
      - name: BUILD DOCKER IMAGE (PRODUCTION)
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        run: |
          buildah build -t ${{ steps.string.outputs.lowercase }} .
      - name: BUILD DOCKER IMAGE (STAGING)
        if: ${{ github.ref_name == 'devel' ||  github.ref_name == 'develop' || github.ref_name == 'development' }}
        run: |
          buildah build -t ${{ steps.string.outputs.lowercase }}-dev .
      # - name: PWD
      #   run: pwd
      # - name: List files
      #   run: ls
      # - name: List files
      #   run: ls ../
      - name: RUN DOCKER IMAGE (PRODUCTION)
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        run: |
          buildah tag ${{ steps.string.outputs.lowercase }} 10.43.32.58:5000/${{ steps.string.outputs.lowercase }}
          buildah push --tls-verify=false 10.43.32.58:5000/${{ steps.string.outputs.lowercase }}
        # run: buildah push ${{ steps.string.outputs.lowercase }}
      - name: RUN DOCKER IMAGE (STAGING)
        if: ${{ github.ref_name == 'devel' ||  github.ref_name == 'develop' || github.ref_name == 'development' }}
        run: |
          buildah tag ${{ steps.string.outputs.lowercase }}-dev 10.43.32.58:5000/${{ steps.string.outputs.lowercase }}-dev
          buildah push --tls-verify=false 10.43.32.58:5000/${{ steps.string.outputs.lowercase }}-dev
        # run: buildah push ${{ steps.string.outputs.lowercase }}-dev
      - name: RUN DOCKER PRUNE CONTAINERS
        run: |
          for container in $(buildah containers --quiet); do status=$(buildah inspect --type container $container --format '{{.State.Status}}') && [ "$status" == "exited" ] && buildah rm $container; done
      - name: RUN DOCKER PRUNE IMAGES
        run: |
          for image in $(buildah images --filter "dangling=true" --quiet); do buildah rmi $image; done
      # - name: Kill pod (PRODUCTION)
      #   if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
      #   run: |
      #     kubectl delete pods -l app=${{ steps.string.outputs.lowercase }}-app
      # - name: Kill pod (STAGING)
      #   if: ${{ github.ref_name == 'devel' ||  github.ref_name == 'develop' || github.ref_name == 'development' }}
      #   run: |
      #     kubectl delete pods -l app=${{ steps.string.outputs.lowercase }}-app-dev
      - name: Delete folder
        run: |
          rm -rf ../${{ github.event.repository.name }}/*
